name: freeily
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+42

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: any
  provider: ^4.3.3
  flutter_bloc: ^6.1.3
  intl: any
  font_awesome_flutter: ^9.0.0
  flutter_secure_storage: ^4.1.0
  google_sign_in: ^4.5.9
  socket_io_client: ^1.0.1
  animations: ^2.0.0
  animate_do: ^2.0.0
  google_maps_flutter: ^1.2.0
  location: ^3.2.4
  permission_handler: ^5.1.0+2
  rxdart: ^0.27.0
  universal_platform: ^1.0.0+1
  flutter_slidable: ^0.6.0
  universal_html: ^1.2.4
  shared_preferences: ^0.5.12+4
  image_picker: ^0.6.7+22
  mime_type: ^1.0.0
  http_parser: ^3.1.4
  carousel_slider: ^4.0.0
  sign_in_with_apple: ^3.1.0
  cached_network_image: ^2.0.0
  feature_discovery: ^0.13.0+2
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  url_launcher: ^5.7.10
  card_swiper: ^1.0.4
  expandable: ^5.0.1
  firebase_messaging: ^8.0.0-dev.7
  flutter_credit_card: ^2.0.0
  #stripe_payment: ^1.1.4
  palette_generator: ^0.3.1
  #firebase_analytics: ^7.0.1
  
 

 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/freeily-icon.jpg"

flutter_native_splash:
  image: assets/icons/logo7.png
  ios: true
  color: "#0F0F0F"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/logos/logos_banks/
    - assets/icons/
    - assets/empty/
    - assets/on_board/
  



    