name: freeily
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+30

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: any
  provider: ^5.0.0
  intl: any
  font_awesome_flutter: ^9.0.0
  flutter_secure_storage: ^4.1.0
  google_sign_in: ^5.0.7
  socket_io_client: ^0.9.12
  animations: ^2.0.0
  animate_do: ^1.7.5
  google_maps_flutter: ^2.0.3
  geolocator: ^7.0.3
  flutter_bloc: ^7.0.0
  permission_handler: ^7.1.0
  rxdart: ^0.27.0
  universal_platform: ^0.1.3
  flutter_slidable: ^0.6.0
  universal_html: ^2.0.8
  shared_preferences: ^2.0.5
  image_picker: ^0.7.5+2
  mime_type: ^1.0.0
  http_parser: ^4.0.0
  carousel_slider: ^3.0.0
  sign_in_with_apple: ^3.0.0
  cached_network_image: ^3.0.0
  feature_discovery: ^0.14.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  url_launcher: ^6.0.9
  flutter_masked_text: ^0.8.0
  flutter_swiper: ^1.1.6
  expandable: ^5.0.1
  firebase_messaging: ^10.0.4
  flutter_credit_card: ^2.0.0
  stripe_payment: ^1.1.4
  palette_generator: ^0.3.1
  
 

 
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/freeily-icon.jpg"

flutter_native_splash:
  image: assets/icons/logo7.png
  ios: true
  color: "#0F0F0F"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/logos/logos_banks/
    - assets/icons/
    - assets/empty/
    - assets/on_board/
  



    