name: australti_ecommerce_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_fonts: any
  provider: ^5.0.0
  intl: any
  font_awesome_flutter: ^9.0.0
  flutter_secure_storage: ^4.1.0
  google_sign_in: ^5.0.1
  socket_io_client: ^0.9.12
  animations: ^2.0.0
  animate_do: ^1.7.5
  modal_bottom_sheet: ^2.0.0
  dio: ^4.0.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  flutter_bloc: ^7.0.0
  permission_handler: ^7.1.0
  geocoder: ^0.2.1
  rxdart: ^0.27.0
  universal_platform: ^0.1.3
  flutter_slidable: ^0.6.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/empty/
    - assets/nike_shoes_store/
    - assets/vinyl_album/
    - assets/dbrand_skin_selection/
    - assets/multiple_card_flow/
    - assets/grocery_store/
    - assets/travel_photos/
    - assets/batman_sign_up/
    - assets/rappi_concept/
    - assets/pizza_order/


    